# Site Info
title:              "老洞"
description:        "老洞是一个分享脑洞的地方"
# google_verify:      epFgX0s_0RM3CdjwFcsewfXzPov2g8s9ZBOLyaIUH-o # Put your Google Verification here
# google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code

# Author Info
author_name:        "阿荡" # Your name here
author_email:       brainhole.fun@outlook.com # Your email here
author_gravatar:    5a6027cf564fa32ef226d71905f057ec # Your Gravatar md5 hash here for logo
# twitter_username:   HeiswayiNrird # Your Twitter username here
github_username:    lisnb # Your GitHub username here

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
# permalink:          /:title # Post permalink
timezone:           Asia/Shanghai # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to false to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

host: 0.0.0.0
port: 4000

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
